
server:
  port: 7171
spring:
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 7
        min-idle: 2
        max-idle: 7
        max-wait: -1ms
      shutdown-timeout: 200ms
  datasource:
    url: jdbc:mysql://localhost:3306/banco
    username: accounts
    password: JQK0Lqgt0v6JfBJg
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
app:
  url: /login
  header: Authorization
  prefix: Bearer
  expiration: 36000
  secret: claveSecreta


   
      